export const labels = {
  title: "Organization",
  search: "search",
  editOrganization: "Edit Organization",
  orgNotFound: "Organization Not Found",
  searchPlaceholder: "Search",
  name: "Name",
  tagline: "Tagline",
  banner: "Banner",
  orgURL: "Organization URL",
  borderRadius: "Border Radius",
  buttonColors: "Button Colors",
  authMethod: "Authentication Method",
  actions: "Actions",
  edit: "Edit",
  delete: "Delete",
  update: "Update",
  lightMode: "Light Mode",
  darkMode: "Dark Mode"
};
